import Head from 'next/head'
import Container from '@mui/material/Container';
import Header from "../components/header"
import SingleCard from '@/components/singleCard';
import Grid from '@mui/material/Grid';

const testCardNum = [1,2,3,4,5,6,7,8,8,8,8,8,8]

export default function Home() {
  return (
    <>
      <Head>
        <title>The Honest Machine</title>
        <meta name="description" content="Automated Blog page, content generated by a machine AI with no human intervention" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Header></Header>
      <Container maxWidth="xl" style={{ 'padding': "20px" }}>
        <Grid container spacing={2}>
          {
            testCardNum.map((item, i) => {
              return <Grid item><SingleCard key={i}></SingleCard></Grid>
            })
          } 
        </Grid>
      </Container>
    </>
  )
}
