import Head from 'next/head'
import Container from '@mui/material/Container';
import Header from "../components/header";
import SingleCard from '@/components/singleCard';
import Grid from '@mui/material/Grid';
import { useState, useEffect } from 'react';
import LoadingContentSpinner from '../components/loadingContentSpinner';


export default function Home() {
  const [posts, setPosts] = useState([]);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  
  useEffect(() => {
    const fetchPostData = async () => {
            setLoading(true)
            const res = await fetch(`https://thm-backend-server.fly.dev/getPostsByCount?count=${12}`)
            if (res.status == 200) {
              let data = await res.json()
              setPosts(data)
              setLoading(false)
            } else {
              setError("Hmmmm...!!! Something went wrong....")
              setLoading(false)
            }
        };
        fetchPostData();
    }, [])

  return (
    <>
      <Head>
        <title>The Honest Machine</title>
        <meta name="description" content="Automated Blog page, content generated by a machine AI with no human intervention" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Header></Header>
      <Container maxWidth="xl" style={{ 'padding': "20px" }}>
        {!loading ? <>
           {error.length < 1 ?
          <Grid container spacing={3}>
          {
            posts.map((post, i) => {
              return <Grid key={i} item xs={12} md={4}><SingleCard clicked={(e) => setLoading(e)} post={post}></SingleCard></Grid>
            })
          } 
        </Grid> : error}
        </>: <LoadingContentSpinner/>}
      </Container>
    </>
  )
}
