import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '../components/header'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>The Honest Machine</title>
        <meta name="description" content="Automated Blog page, content generated by a machine AI with no human intervention" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Header></Header>
      <main className={styles.main}>
        HEY THERE
      </main>
    </>
  )
}
